-- migrate:up

-- `if_fio_cz_transactions_tsdb_ext`
-- A tsdb compatible table storing raw (unparsed) data imported from the external upstream.
-- rev_uuid is generated by default, CTE insert statement *must* be used to ensure a 1:1 uuid:ext_id mapping
-- documents with different nonces for the same extid correspond to extid document revisions, the latest revision is recognized by highest created_at
CREATE TABLE "glued"."if_fio_cz_transactions_tsdb_ext" (
    rev_uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    doc jsonb NOT NULL,
    nonce bytea GENERATED ALWAYS AS (decode(md5((doc::text)), 'hex')) STORED,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ext_id text GENERATED ALWAYS AS (doc ->> 'ID_SKL_POLOZKA'::text) STORED NOT NULL,
    PRIMARY KEY (nonce, created_at)  -- Ensure unique combination of document content and timestamp
);
CREATE INDEX idx_if_fio_cz_transactions_ext_id_created_at ON if_fio_cz_transactions_tsdb_ext (ext_id, created_at DESC);



-- `if_fio_cz_transactions_tsdb`
-- A tsdb compatible table storing records from if_fio_cz_transactions_tsdb_ext transformed to their final internal representation.
-- uuid must be a defined key having a valid value in doc (equal to that of if_fio_cz_transactions_tsdb_ext.uuid)
-- created_at must be a defined key having a valid value (equal to that of if_fio_cz_transactions_tsdb_ext.created_at)
-- documents with different nonces for the same ext_id/uuid correspond to ext_id/uuid document revisions, the latest revision is recognized by highest created_at
CREATE TABLE "glued"."if_fio_cz_transactions_tsdb" (
    rev_uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    uuid uuid generated always as (((doc->>'uuid'::text))::uuid) stored not null,
    doc jsonb NOT NULL,
    nonce bytea generated always as (decode(md5(((doc - 'uuid')::text)), 'hex')) stored,
    created_at timestamp with time zone not null,
    ext_id text generated always as (doc -> 'refs' ->> 'akord:ID_SKL_POLOZKA'::text) stored not null,
    sku text GENERATED ALWAYS AS (doc -> 'refs' ->> 'akord:SKU'::text) STORED,
    PRIMARY KEY (nonce, created_at)  -- Ensure unique combination of document content and timestamp
);
CREATE INDEX idx_if_fio_cz_transactions_uuid_created_at ON if_fio_cz_transactions_tsdb (uuid, created_at DESC);
CREATE INDEX idx_if_fio_cz_transactions_sku ON if_fio_cz_transactions_tsdb (sku);

-- migrate:down

DROP TABLE IF EXISTS "glued"."if_fio_cz_transactions_tsdb";
DROP TABLE IF EXISTS "glued"."if_fio_cz_transactions_tsdb_ext";
